// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.3
// source: protobufs/anomaly.proto

package turiondatapacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for telemetry message field names. Used for identifying anomalies.
type Field int32

const (
	// must start at 0
	Field_FIELD_UNSPECIFIED Field = 0
	Field_TEMPERATURE       Field = 1
	Field_BATTERY           Field = 2
	Field_ALTITUDE          Field = 3
	Field_SIGNAL            Field = 4
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "TEMPERATURE",
		2: "BATTERY",
		3: "ALTITUDE",
		4: "SIGNAL",
	}
	Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"TEMPERATURE":       1,
		"BATTERY":           2,
		"ALTITUDE":          3,
		"SIGNAL":            4,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufs_anomaly_proto_enumTypes[0].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_protobufs_anomaly_proto_enumTypes[0]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_protobufs_anomaly_proto_rawDescGZIP(), []int{0}
}

// Anomaly represents a single out-of-range reading.
type Anomaly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp uint64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Field     Field   `protobuf:"varint,3,opt,name=field,proto3,enum=turiondatapacket.Field" json:"field,omitempty"`
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_protobufs_anomaly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_anomaly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_protobufs_anomaly_proto_rawDescGZIP(), []int{0}
}

func (x *Anomaly) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Anomaly) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Anomaly) GetField() Field {
	if x != nil {
		return x.Field
	}
	return Field_FIELD_UNSPECIFIED
}

var File_protobufs_anomaly_proto protoreflect.FileDescriptor

var file_protobufs_anomaly_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x75, 0x72, 0x69, 0x6f,
	0x6e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x6c, 0x0a, 0x07, 0x41,
	0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x74, 0x75, 0x72, 0x69,
	0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2a, 0x56, 0x0a, 0x05, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x45, 0x4d,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x41,
	0x54, 0x54, 0x45, 0x52, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4c, 0x54, 0x49, 0x54,
	0x55, 0x44, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x4c, 0x10,
	0x04, 0x42, 0x34, 0x5a, 0x32, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x75, 0x72, 0x69, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x3b, 0x74, 0x75, 0x72, 0x69, 0x6f, 0x6e, 0x64, 0x61, 0x74,
	0x61, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_anomaly_proto_rawDescOnce sync.Once
	file_protobufs_anomaly_proto_rawDescData = file_protobufs_anomaly_proto_rawDesc
)

func file_protobufs_anomaly_proto_rawDescGZIP() []byte {
	file_protobufs_anomaly_proto_rawDescOnce.Do(func() {
		file_protobufs_anomaly_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_anomaly_proto_rawDescData)
	})
	return file_protobufs_anomaly_proto_rawDescData
}

var file_protobufs_anomaly_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobufs_anomaly_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobufs_anomaly_proto_goTypes = []any{
	(Field)(0),      // 0: turiondatapacket.Field
	(*Anomaly)(nil), // 1: turiondatapacket.Anomaly
}
var file_protobufs_anomaly_proto_depIdxs = []int32{
	0, // 0: turiondatapacket.Anomaly.field:type_name -> turiondatapacket.Field
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_anomaly_proto_init() }
func file_protobufs_anomaly_proto_init() {
	if File_protobufs_anomaly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_anomaly_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufs_anomaly_proto_goTypes,
		DependencyIndexes: file_protobufs_anomaly_proto_depIdxs,
		EnumInfos:         file_protobufs_anomaly_proto_enumTypes,
		MessageInfos:      file_protobufs_anomaly_proto_msgTypes,
	}.Build()
	File_protobufs_anomaly_proto = out.File
	file_protobufs_anomaly_proto_rawDesc = nil
	file_protobufs_anomaly_proto_goTypes = nil
	file_protobufs_anomaly_proto_depIdxs = nil
}
